# Generated by Django 5.1.7 on 2025-05-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_favorite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='content_type',
        ),
    ]
