# Generated by Django 5.1.7 on 2025-05-12 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_favorite', '0002_remove_favorite_content_type'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='content_type',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
