# Generated by Django 5.1.7 on 2025-05-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_favorite', '0003_favorite_content_type_alter_favorite_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='object_id',
            field=models.CharField(),
        ),
    ]
