# Generated by Django 5.1.4 on 2025-01-13 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('b', 'books'), ('c', 'chancellery')], max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('articul', models.BigIntegerField(unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('img_url', models.CharField(default='https://cdn-icons-png.flaticon.com/512/2175/2175188.png', max_length=255)),
            ],
            options={
                'db_table': 'api_products',
            },
        ),
        migrations.CreateModel(
            name='BooksAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'api_category',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=3)),
                ('start_data', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'api_discount',
            },
        ),
        migrations.CreateModel(
            name='Chancellery',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.products')),
            ],
            options={
                'db_table': 'api_chancellery',
            },
            bases=('api.products',),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category'),
        ),
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.discount'),
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=2000)),
                ('date_publish', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_user_review',
            },
        ),
        migrations.CreateModel(
            name='ReviewRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.BooleanField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userreview')),
            ],
            options={
                'db_table': 'api_review_rate',
            },
        ),
        migrations.CreateModel(
            name='ProductUserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products')),
                ('user_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userreview')),
            ],
            options={
                'db_table': 'api_product_user_review',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='reviews',
            field=models.ManyToManyField(blank=True, through='api.ProductUserReview', to='api.userreview'),
        ),
        migrations.CreateModel(
            name='UsersRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rate', models.BooleanField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_users_rate',
            },
        ),
        migrations.CreateModel(
            name='ProductUserRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products')),
                ('user_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usersrate')),
            ],
            options={
                'db_table': 'api_product_user_rate',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='rate',
            field=models.ManyToManyField(blank=True, null=True, through='api.ProductUserRate', to='api.usersrate'),
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.products')),
                ('publisher', models.CharField(max_length=155)),
                ('series', models.CharField(blank=True, max_length=155, null=True)),
                ('binding', models.CharField(choices=[('Т', 'Твердый'), ('М', 'Мягкий')], max_length=155)),
                ('pub_year', models.IntegerField()),
                ('count_pages', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.booksauthors')),
            ],
            options={
                'db_table': 'api_books',
            },
            bases=('api.products',),
        ),
    ]
