# Generated by Django 5.1.3 on 2025-01-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='second_url',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
