# Generated by Django 5.1.4 on 2025-01-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booksauthors',
            old_name='author',
            new_name='name',
        ),
    ]
