# Generated by Django 5.1.3 on 2024-12-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_products_second_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='second_image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
