# Generated by Django 5.1.3 on 2024-12-21 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userreview_date_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.BooleanField(null=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
