# Generated by Django 5.1.2 on 2024-10-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img_url',
            field=models.CharField(default='1212'),
            preserve_default=False,
        ),
    ]
