# Generated by Django 5.1.3 on 2024-12-22 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reviewrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrate',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.products'),
            preserve_default=False,
        ),
    ]
