# Generated by Django 5.1.3 on 2024-12-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_reviewrate_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='second_image',
        ),
        migrations.AlterField(
            model_name='products',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='api.userreview'),
        ),
    ]
