# Generated by Django 5.1.2 on 2024-10-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_products_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
        migrations.AlterField(
            model_name='products',
            name='articul',
            field=models.BigIntegerField(unique=True),
        ),
    ]
