# Generated by Django 5.1.2 on 2024-10-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_products_slug_alter_products_articul'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date_add',
            field=models.DateField(auto_now_add=True, default='2024-10-30'),
            preserve_default=False,
        ),
    ]
