# Generated by Django 5.1.3 on 2025-01-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_products_second_image_alter_products_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersrate',
            name='product',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rate',
        ),
        migrations.AddField(
            model_name='products',
            name='rate',
            field=models.ManyToManyField(blank=True, null=True, to='api.usersrate'),
        ),
    ]
