# Generated by Django 5.1.3 on 2025-01-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_usersrate_product_remove_products_rate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRate',
        ),
    ]
