# Generated by Django 5.1.6 on 2025-02-24 20:34

import django_ulid.models
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='Анонимный', max_length=155),
        ),
        migrations.AddField(
            model_name='users',
            name='surname',
            field=models.CharField(default='Пользователь', max_length=155),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
    ]
