# Generated by Django 5.1.7 on 2025-03-24 15:50

import django_ulid.models
import ulid.api.api
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0005_remove_favourite_product_remove_favourite_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
    ]
