# Generated by Django 5.1.7 on 2025-04-05 16:33

import django.db.models.deletion
import django_ulid.models
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/products/')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chancellery',
            fields=[
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=564, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('articul', models.CharField(max_length=50, unique=True)),
                ('main_image', models.FileField(default='media/default/product-default.png', upload_to='media/products/')),
                ('date_add', models.DateField(auto_now_add=True)),
                ('content_type', models.CharField(choices=[('book', 'Книги'), ('chancellery', 'Канцелярия')])),
                ('ancillary_images', models.ManyToManyField(to='api_products.productimages')),
                ('subcat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_products.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('subcats', models.ManyToManyField(to='api_products.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=564, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('articul', models.CharField(max_length=50, unique=True)),
                ('main_image', models.FileField(default='media/default/product-default.png', upload_to='media/products/')),
                ('date_add', models.DateField(auto_now_add=True)),
                ('content_type', models.CharField(choices=[('book', 'Книги'), ('chancellery', 'Канцелярия')])),
                ('publisher', models.CharField(max_length=155)),
                ('series', models.CharField(blank=True, max_length=155, null=True)),
                ('binding', models.CharField(choices=[('Т', 'Твердый'), ('М', 'Мягкий')], max_length=155)),
                ('pub_year', models.IntegerField()),
                ('count_pages', models.IntegerField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_products.author')),
                ('ancillary_images', models.ManyToManyField(to='api_products.productimages')),
                ('subcat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_products.subcategory')),
            ],
            options={
                'db_table': 'api_books',
            },
        ),
    ]
