# Generated by Django 5.1.6 on 2025-02-15 12:38

import django.db.models.deletion
import django_ulid.models
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('b', 'books'), ('c', 'chancellery')], max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('articul', models.BigIntegerField(unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('img_url', models.CharField(default='https://cdn-icons-png.flaticon.com/512/2175/2175188.png', max_length=255)),
            ],
            options={
                'db_table': 'api_products',
            },
        ),
        migrations.CreateModel(
            name='BooksAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'api_category',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=3)),
                ('start_data', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'api_discount',
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=2000)),
                ('date_publish', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_user_review',
            },
        ),
        migrations.CreateModel(
            name='UsersRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rate', models.BooleanField(default=None, null=True)),
            ],
            options={
                'db_table': 'api_users_rate',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_products.products')),
                ('publisher', models.CharField(max_length=155)),
                ('series', models.CharField(blank=True, max_length=155, null=True)),
                ('binding', models.CharField(choices=[('Т', 'Твердый'), ('М', 'Мягкий')], max_length=155)),
                ('pub_year', models.IntegerField()),
                ('count_pages', models.IntegerField()),
            ],
            options={
                'db_table': 'api_books',
            },
            bases=('api_products.products',),
        ),
        migrations.CreateModel(
            name='Chancellery',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_products.products')),
            ],
            options={
                'db_table': 'api_chancellery',
            },
            bases=('api_products.products',),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_products.category'),
        ),
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_products.discount'),
        ),
        migrations.CreateModel(
            name='ProductUserRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_products.products')),
            ],
            options={
                'db_table': 'api_product_user_rate',
            },
        ),
        migrations.CreateModel(
            name='ProductUserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_products.products')),
            ],
            options={
                'db_table': 'api_product_user_review',
            },
        ),
        migrations.CreateModel(
            name='ReviewRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.BooleanField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_products.products')),
            ],
            options={
                'db_table': 'api_review_rate',
            },
        ),
    ]
