# Generated by Django 5.1.6 on 2025-02-15 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreview',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewrate',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_products.userreview'),
        ),
        migrations.AddField(
            model_name='productuserreview',
            name='user_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_products.userreview'),
        ),
        migrations.AddField(
            model_name='products',
            name='reviews',
            field=models.ManyToManyField(blank=True, through='api_products.ProductUserReview', to='api_products.userreview'),
        ),
        migrations.AddField(
            model_name='usersrate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productuserrate',
            name='user_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_products.usersrate'),
        ),
        migrations.AddField(
            model_name='products',
            name='rate',
            field=models.ManyToManyField(blank=True, null=True, through='api_products.ProductUserRate', to='api_products.usersrate'),
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_products.booksauthors'),
        ),
    ]
