# Generated by Django 5.1.6 on 2025-02-24 20:34

import django_ulid.models
import ulid.api.api
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
    ]
