# Generated by Django 5.1.7 on 2025-03-23 19:40

import django_ulid.models
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_products', '0005_alter_products_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.RemoveField(
            model_name='books',
            name='products_ptr',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='chancellery',
            name='products_ptr',
        ),
        migrations.RemoveField(
            model_name='products',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='productuserrate',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productuserrate',
            name='user_rate',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='productuserreview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productuserreview',
            name='user_review',
        ),
        migrations.RemoveField(
            model_name='products',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='reviewrate',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reviewrate',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewrate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='usersrate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='products',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='products',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='products',
            name='type',
        ),
        migrations.AddField(
            model_name='products',
            name='desc',
            field=models.CharField(max_length=564, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='articul',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='products',
            table=None,
        ),
        migrations.DeleteModel(
            name='BooksAuthors',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Chancellery',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='ProductUserRate',
        ),
        migrations.DeleteModel(
            name='ProductUserReview',
        ),
        migrations.DeleteModel(
            name='ReviewRate',
        ),
        migrations.DeleteModel(
            name='UserReview',
        ),
        migrations.DeleteModel(
            name='UsersRate',
        ),
    ]
