# Generated by Django 5.1.7 on 2025-03-24 16:22

import django.db.models.deletion
import django_ulid.models
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_products', '0006_remove_books_author_remove_books_products_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=564, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('articul', models.CharField(max_length=50, unique=True)),
                ('main_image', models.FileField(default='media/default/product-default.png', upload_to='media/products/')),
                ('publisher', models.CharField(max_length=155)),
                ('series', models.CharField(blank=True, max_length=155, null=True)),
                ('binding', models.CharField(choices=[('Т', 'Твердый'), ('М', 'Мягкий')], max_length=155)),
                ('pub_year', models.IntegerField()),
                ('count_pages', models.IntegerField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_products.author')),
            ],
            options={
                'db_table': 'api_books',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chancellery',
            fields=[
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=564, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('articul', models.CharField(max_length=50, unique=True)),
                ('main_image', models.FileField(default='media/default/product-default.png', upload_to='media/products/')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_products.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/products/')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='book',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_products.category'),
        ),
        migrations.AddField(
            model_name='chancellery',
            name='ancillary_images',
            field=models.ManyToManyField(to='api_products.productimages'),
        ),
        migrations.AddField(
            model_name='book',
            name='ancillary_images',
            field=models.ManyToManyField(to='api_products.productimages'),
        ),
    ]
