# Generated by Django 5.1.7 on 2025-03-24 16:47

import django.db.models.deletion
import django_ulid.models
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_products', '0007_author_book_category_chancellery_productimages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='chancellery',
            name='cat',
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chancellery',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='book',
            name='subcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_products.subcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='subcats',
            field=models.ManyToManyField(to='api_products.subcategory'),
        ),
        migrations.AddField(
            model_name='chancellery',
            name='subcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_products.subcategory'),
        ),
    ]
