# Generated by Django 5.1.7 on 2025-04-02 18:51

import django_ulid.models
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_products', '0011_alter_author_id_alter_book_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content_type',
            field=models.CharField(choices=[('book', 'Книги'), ('chancellery', 'Канцелярия')], default='book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chancellery',
            name='content_type',
            field=models.CharField(choices=[('book', 'Книги'), ('chancellery', 'Канцелярия')], default='chancellery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chancellery',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
    ]
